version: 2

models:
  - name: dim_patients
    description: Dimension table for enriched patient data.
    columns:
      - name: patient_id
        description: This is a unique identifier for  patients
        tests:
          - not_null
          - unique

  - name: fct_patient_claims_summary
    description: This fact table summarizes  data per patient
    columns:
      - name: patient_id
        description: Foreign key to dim_patients.
        tests:
          - not_null
          - relationships:
              to: ref('dim_patients')
              field: patient_id

  - name: stg_patient_claims
    description: Cleaned version of raw claims data.
    columns:
      - name: claim_id
        description: Unique claim identifierr
        tests:
          - not_null
          - unique
      - name: patient_id
        description: Reference to patient ID.
        tests:
          - not_null
